Add comments and clean up code

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -20,7 +20,7 @@ fi
 # checksum function returns checksum of current configuration.
 checksum() {
   (
-    cat $0 2>/dev/null
+    cat $0 2>/dev/null # vendor/gems
     cat .ruby-version 2>/dev/null
     cat Brewfile 2>/dev/null
     cat Gemfile Gemfile.lock 2>/dev/null
@@ -33,56 +33,53 @@ checksum() {
 bundler_args="--path vendor/gems"
 checksum_args="${bundler_args}" # if we change the path also rev the checksum.
 
-# Check the checksum.
+# Check the checksum.and exit early if everything is up to date
 checksum_path=.bundle/checksum
-if [ "x${force}" != "yes" ]; then
-  if [ "x`cat ${checksum_path} 2>/dev/null`" = "x`checksum ${checksum_args}`" ]; then
-    if [ -z "${quiet}" ]; then
-      echo Bundle is up-to-date.
-    fi
-    exit 0
-  fi
+if [ "x`cat ${checksum_path} 2>/dev/null`" = "x`checksum ${checksum_args}`" ]; then
+  echo Bundle is up-to-date.
+  exit 0
 fi
 
-# only do these things on OS X
-if [ "$(uname -s)" = "Darwin" ]; then
-  echo "==> Running brew bundle"
-  brew update >/dev/null
-  brew bundle check &>/dev/null || brew bundle
+echo "==> Running brew bundle"
+brew update >/dev/null
+brew bundle check &>/dev/null || brew bundle
 
-  abort_with_shell_setup_message() {
-    case $(basename ${SHELL:-bash}) in
-    sh|bash)
-      echo 'Error: add `eval "$(rbenv init -)"` to the end of your .bash_profile!' >&2; exit 1
-      ;;
-    zsh)
-      echo 'Error: add `eval "$(rbenv init -)"` to the end of your .zshrc!' >&2; exit 1
-      ;;
-    *)
-      echo 'Error: you must finish setting up rbenv in your shell; check `rbenv init` for instructions!' >&2; exit 1
-    esac
-  }
+# Install ruby version from .ruby-version
+rbenv install --skip-existing `rbenv version-name`
 
-  rbenv install --skip-existing `rbenv version-name`
-
-  (rbenv which bundle &>/dev/null && bundle -v &>/dev/null) || {
-    # bug with bundler https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html
-    bundler_version=`cat Gemfile.lock | grep -A 1 "BUNDLED WITH" | tail -1`
-    gem install bundler -v $bundler_version
-    gem install foreman
-    rbenv rehash
-  }
+# Check if rbenv configuration is in shell config
+if [ "$(rbenv exec ruby --version)" != "$(ruby --version)" ]; then
+  case $(basename ${SHELL:-bash}) in
+  sh|bash)
+    echo 'Error: add `eval "$(rbenv init -)"` to the end of your .bash_profile!' >&2
+    ;;
+  zsh)
+    echo 'Error: add `eval "$(rbenv init -)"` to the end of your .zshrc!' >&2
+    ;;
+  *)
+    echo 'Error: you must finish setting up rbenv in your shell; check `rbenv init` for instructions!' >&2
+  esac
+  exit 1
 fi
 
-bundle install $bundler_args
+# Install bundler and foreman
+(rbenv which bundle &>/dev/null && bundle -v &>/dev/null) || {
+  # bug with bundler https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html
+  bundler_version=`cat Gemfile.lock | grep -A 1 "BUNDLED WITH" | tail -1`
+  gem install bundler -v $bundler_version
+  gem install foreman
+  rbenv rehash
+}
 
-# ensure gems are all installed
+# Install gems
 echo "==> Installing gem dependencies…"
+bundle install $bundler_args
 bundle check --path vendor/gems 2>&1 > /dev/null || {
   bundle install --path vendor/gems --quiet --without production
   bundle package --all
 }
 
+# Update checksum
 checksum ${checksum_args} > ${checksum_path}
 
 echo "x`cat ${checksum_path} 2>/dev/null`"
diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -5,12 +5,14 @@ set -e
 
 script/bootstrap
 
-set -x
-
 echo "==> Turning on postgresql"
-echo "If fails to turn on check error logs /usr/local/var/log/postgres.log"
-echo "If error is 'The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 12.1.' run 'brew postgresql-upgrade-database'"
 brew services start postgresql
+if ! pg_ctl -D /usr/local/var/postgres status; then
+  echo "failed to start postgresql"
+  echo "check error logs /usr/local/var/log/postgres.log"
+  echo "If error is 'The data directory was initialized by PostgreSQL version x.x, which is not compatible with this version x.x.' run 'brew postgresql-upgrade-database'"
+  exit 1
+fi
 
 echo "==> Setting up databases"
 bin/rake db:drop
